### ISSUE TITLE
ModuleNotFoundError:no module named carla_gym.env

### ISSUE THREAD

**Issue by YYan99** [ShuaibinLi/RL_CARLA#1]

**Comment by ShuaibinLi** [comment]
### Fixed
Thanks for reminding

**Comment by YYan99** [comment]
> ### Fixed
> 
> Thanks for reminding

Thanks,but new error exist:ModuleNotFoundError: No module named 'gym_carla.envs'

**Comment by ShuaibinLi** [comment]
> > ### Fixed
> > Thanks for reminding
> 
> Thanks,but new error exist:ModuleNotFoundError: No module named 'gym_carla.envs'

I've checked that, there is nothing wrong with gym_carla. 
Maybe you can `pip uninstall gym_carla` and reinstall it from the repo with `pip install -e .`.

**Comment by ShuaibinLi** [comment]
> > ### Fixed
> > Thanks for reminding
> 
> Thanks,but new error exist:ModuleNotFoundError: No module named 'gym_carla.envs'

Maybe you can put your detailed error here, any codes or pic

**Comment by YYan99** [comment]
> > > ### Fixed
> > > Thanks for reminding
> > 
> > 
> > Thanks,but new error exist:ModuleNotFoundError: No module named 'gym_carla.envs'
> 
> Maybe you can put your detailed error here, any codes or pic
```
Traceback  (most recent call last):
  File "train.py", line 142, in <module>
    main()
  File "train.py", line 47, in main
    eval_env = LocalEnv(args.env, eval_env_params)
  File "/home/yy/RL_CARLA/env_utils.py", line 66, in __init__
    self.env = gym.make(env_name, params=params)
  File "/home/yy/anaconda2/envs/rl_carla/lib/python3.6/site-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/home/yy/anaconda2/envs/rl_carla/lib/python3.6/site-packages/gym/envs/registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "/home/yy/anaconda2/envs/rl_carla/lib/python3.6/site-packages/gym/envs/registration.py", line 72, in make
    cls = load(self._entry_point)
  File "/home/yy/anaconda2/envs/rl_carla/lib/python3.6/site-packages/gym/envs/registration.py", line 17, in load
    mod = importlib.import_module(mod_name)
  File "/home/yy/anaconda2/envs/rl_carla/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'gym_carla.envs'
```
Thanks for your reply. I have used the method above, but it doesn't work. Here are the error codes.

**Comment by ShuaibinLi** [comment]
Some file has changed, please reclone this repo and retry it.

**Comment by YYan99** [comment]
> Some file has changed, please reclone this repo and retry it.

I have recloned the repo twice, and rebuild the conda environment, these methods don't work. The error code is same as above.

**Comment by ShuaibinLi** [comment]
> > Some file has changed, please reclone this repo and retry it.
> 
> I have recloned the repo twice, and rebuild the conda environment, these methods don't work. The error code is same as above.

Find the '__init__' error you mentioned, fixed.
Please reclone and try it another time.
Thanks for your patience.
You can open port2029 and run evaluate.py for a quick checkout.

**Comment by YYan99** [comment]
> > > Some file has changed, please reclone this repo and retry it.
> > 
> > 
> > I have recloned the repo twice, and rebuild the conda environment, these methods don't work. The error code is same as above.
> 
> Find the '**init**' error you mentioned, fixed.
> Please reclone and try it another time.
> Thanks for your patience.
> You can open port2029 and run evaluate.py for a quick checkout.

Thanks for your reply, it works.

**Comment by USTC-ZS** [comment]
> > > > Some file has changed, please reclone this repo and retry it.
> > > 
> > > 
> > > I have recloned the repo twice, and rebuild the conda environment, these methods don't work. The error code is same as above.
> > 
> > 
> > Find the '**init**' error you mentioned, fixed.
> > Please reclone and try it another time.
> > Thanks for your patience.
> > You can open port2029 and run evaluate.py for a quick checkout.
> 
> Thanks for your reply, it works.

I ran into the same problem.  What does “Find the 'init' error you mentioned, fixed”mean?    **How to fixed?**

**Comment by YYan99** [comment]
> > > > > Some file has changed, please reclone this repo and retry it.
> > > > 
> > > > 
> > > > I have recloned the repo twice, and rebuild the conda environment, these methods don't work. The error code is same as above.
> > > 
> > > 
> > > Find the '**init**' error you mentioned, fixed.
> > > Please reclone and try it another time.
> > > Thanks for your patience.
> > > You can open port2029 and run evaluate.py for a quick checkout.
> > 
> > 
> > Thanks for your reply, it works.
> 
> I ran into the same problem. What does “Find the 'init' error you mentioned, fixed”mean? **How to fixed?**

Your version of the code is old. Reclone the repo and try again.
