### ISSUE TITLE
No module name 'paddle.nn'

### ISSUE THREAD

**Issue by USTC-ZS** [ShuaibinLi/RL_CARLA#3]
### I have configured conda -env, including **paddlepaddle-gpu==1.18.5  pgl==1.2.1** But iusses existed as follow:
![2021-03-24 19-47-38屏幕截图](https://user-images.githubusercontent.com/55903672/112307877-721b0800-8cdc-11eb-971d-4a71486256a4.png)

### I tested my env, nothing wrong with paddlepaddle-gpu:
![2021-03-24 19-43-50屏幕截图](https://user-images.githubusercontent.com/55903672/112308564-3d5b8080-8cdd-11eb-9bb1-eb4ec47e4b67.png)

Thanks!Please HELP!

**Comment by ShuaibinLi** [comment]
Use paddlepaddle>=2.0.0 instead

**Comment by ShuaibinLi** [comment]
Also,
![image](https://user-images.githubusercontent.com/76139596/112418622-ce296f00-8d64-11eb-807f-3bf575ff6650.png)

**Comment by USTC-ZS** [comment]
> Use paddlepaddle>=2.0.0 instead
It works.  Thanks! But another problem comes out........
![2021-03-25 15-55-44屏幕截图](https://user-images.githubusercontent.com/55903672/112438234-a77a3100-8d82-11eb-9154-4e7e926ec4ae.png)

why?  ModuleNotFoundError: No module named 'gym_carla.envs'
![2021-03-25 15-57-27屏幕截图](https://user-images.githubusercontent.com/55903672/112438391-d0022b00-8d82-11eb-941f-b9455c3c0092.png)
![2021-03-25 15-55-58屏幕截图](https://user-images.githubusercontent.com/55903672/112438408-d55f7580-8d82-11eb-8672-2e7ca3b4b2e3.png)

**Comment by USTC-ZS** [comment]
It works. Thanks, another problem comes out........     **ModuleNotFoundError: No module named 'gym_carla.envs'**
![2021-03-25 15-55-58屏幕截图](https://user-images.githubusercontent.com/55903672/112438818-4f8ffa00-8d83-11eb-9ff8-d5c4008dc2c3.png)

Why ？ I have finished the instruction.
![2021-03-25 15-55-44屏幕截图](https://user-images.githubusercontent.com/55903672/112439044-9d0c6700-8d83-11eb-9c73-e6921a5b4e56.png)
![2021-03-25 15-57-27屏幕截图](https://user-images.githubusercontent.com/55903672/112439065-a1388480-8d83-11eb-861d-09ce80e932fe.png)

**Comment by ShuaibinLi** [comment]
Please reclone this repo, and reinstall gym_carla.
View [Closed issure: no module named carla_gym.env](https://github.com/ShuaibinLi/RL_CARLA/issues/1).

**Comment by USTC-ZS** [comment]
> Please reclone this repo, and reinstall gym_carla.
> View [Closed issure: no module named carla_gym.env](https://github.com/ShuaibinLi/RL_CARLA/issues/1).

**Comment by USTC-ZS** [comment]
> > Please reclone this repo, and reinstall gym_carla.
> > View [Closed issure: no module named carla_gym.env](https://github.com/ShuaibinLi/RL_CARLA/issues/1).

What does “Find the 'init' error you mentioned, fixed”mean? **How to fixed the 'init' error?**  Thanks.

**Comment by ShuaibinLi** [comment]
> > > Please reclone this repo, and reinstall gym_carla.
> > > View [Closed issure: no module named carla_gym.env](https://github.com/ShuaibinLi/RL_CARLA/issues/1).
> 
> What does “Find the 'init' error you mentioned, fixed”mean? **How to fixed the 'init' error?** Thanks.

Just delete the repo, reclone it and do the steps again.
