### ISSUE TITLE
'TorchModel' object has no attribute 'get_actor_params'

### ISSUE THREAD

**Issue by AmeryZhang** [ShuaibinLi/RL_CARLA#5]
After running $ python evaluate.py --restore_model model.ckpt
such an issue was reported in  terminal

**Comment by ShuaibinLi** [comment]
> After running $ python evaluate.py --restore_model model.ckpt such an issue was reported in terminal

`model.ckpt` in the repo was trained and saved from Paddlepaddle, please use Paddlepaddle framework to run the `evaluate.py`
