### ISSUE TITLE
No vehicle

### ISSUE THREAD

**Issue by ConaniLJH** [ShuaibinLi/RL_CARLA#6]
I use the commend " python train.py --xparl_addr localhost:8080", the environment changes, but no vehicle appears, and the environment is a stable one.
Can you tell me why?
(ps: I am using torch framework)

**Comment by ConaniLJH** [comment]
I have checked the log file, and it keeps saying "failed to connect to carla server", why is that?

**Comment by ShuaibinLi** [comment]
`localhost:8080` is just a proxy name, you need to fill in the real address of your own machine.
Please read `README` carefully.
